using System;
using System.Collections.Generic;

namespace sehetak.Models
{
    public partial class Recpersonsdata2
    {
        public string Personcode { get; set; }
        public string Personname { get; set; }
        public string Personadd1 { get; set; }
        public string Personadd2 { get; set; }
        public string Personadd3 { get; set; }
        public DateTime? Personsdate { get; set; }
        public string Ptcode { get; set; }
        public string Ptclassifcode { get; set; }
        public string Personrepres1 { get; set; }
        public string Personrepres2 { get; set; }
        public decimal Origintaxp { get; set; }
        public decimal Custdiscp { get; set; }
        public string Personnote { get; set; }
        public DateTime? Personfdate { get; set; }
        public string Personidno { get; set; }
        public string Personidissue { get; set; }
        public DateTime? Personiddate { get; set; }
        public string Empstime { get; set; }
        public string Empftime { get; set; }
        public decimal? Emptimepermonth { get; set; }
        public decimal Empsalary { get; set; }
        public decimal? Empyrlyoffdays { get; set; }
        public decimal? Empremainoffdays { get; set; }
        public string Branchcode { get; set; }
        public DateTime? Persondofbirth { get; set; }
        public string Empinsuranceno { get; set; }
        public decimal? EmpInsurance { get; set; }
        public decimal PatientPaypercent { get; set; }
        public string Empsocialstatus { get; set; }
        public decimal Emprepresent { get; set; }
        public decimal Empjoballow { get; set; }
        public decimal? Empoldoffdays { get; set; }
        public short? Personslevel { get; set; }
        public string Personsex { get; set; }
        public decimal EmpsalFixed { get; set; }
        public decimal EmpsalVar { get; set; }
        public int? Areacode { get; set; }
        public string SurgeryDoc { get; set; }
        public string AnisythiaDoc { get; set; }
        public string Nurse { get; set; }
        public string ExtclinicDoc { get; set; }
        public string IsDoctor { get; set; }
        public byte? Emptransdir { get; set; }
        public decimal Emphousing { get; set; }
        public decimal Empextra { get; set; }
        public byte? IsDriver { get; set; }
        public DateTime? Retiredate { get; set; }
        public decimal EmpsalSpecial { get; set; }
        public byte? EmpOwner { get; set; }
        public byte? EmpinsuranceInjury { get; set; }
        public byte? IsMaint { get; set; }
        public string Carlicenseno { get; set; }
        public DateTime? Carlicensedate { get; set; }
        public DateTime? Medicalcheckupdate { get; set; }
        public byte? Empattendance { get; set; }
        public byte? Empinsurance1 { get; set; }
        public int? SortOrder { get; set; }
        public byte? Carlicensetype { get; set; }
        public DateTime? Empcontractdate { get; set; }
        public DateTime? LastUpdated { get; set; }
        public int? Expcode { get; set; }
        public string Costcentercode { get; set; }
        public byte Empoldarda { get; set; }
        public byte Empyrlyarda { get; set; }
        public byte Empremainarda { get; set; }
        public string Insurebranchcode { get; set; }
        public string Empinwork { get; set; }
        public DateTime? Empinsurancedate { get; set; }
        public string Empattendtype { get; set; }
        public byte? IsAreamanager { get; set; }
        public byte? IsSupervisor { get; set; }
        public byte? IsRepres { get; set; }
        public byte Empoldsick { get; set; }
        public byte Empyrlysick { get; set; }
        public byte Empremainsick { get; set; }
        public string Ptclassifcode20 { get; set; }
        public string Ptclassifcode30 { get; set; }
        public string Ptclassifcode40 { get; set; }
        public string Ptclassifcode50 { get; set; }
        public string Ptclassifcode60 { get; set; }
        public byte Pausesalary { get; set; }
        public DateTime? Personidenddate { get; set; }
        public byte? Personidtype { get; set; }
        public byte? Onkafala { get; set; }
        public byte? Passporttype { get; set; }
        public string Passportidno { get; set; }
        public string Passportissue { get; set; }
        public DateTime? Passportdate { get; set; }
        public DateTime? Passportenddate { get; set; }
        public byte? Mozawlatype { get; set; }
        public string Mozawlaidno { get; set; }
        public string Mozawlaissue { get; set; }
        public DateTime? Mozawladate { get; set; }
        public DateTime? Mozawlaenddate { get; set; }
        public string Carlicenseissue { get; set; }
        public DateTime? Carlicenseenddate { get; set; }
        public string Empinsuranceissue { get; set; }
        public DateTime? Empinsuranceenddate { get; set; }
        public string Medicalidno { get; set; }
        public string Medicalissue { get; set; }
        public DateTime? Medicaldate { get; set; }
        public byte? Emprisktype { get; set; }
        public string Empriskidno { get; set; }
        public string Empriskissue { get; set; }
        public DateTime? Empriskdate { get; set; }
        public DateTime? Empriskenddate { get; set; }
        public int? Nationality { get; set; }
        public string Prelision { get; set; }
        public short Empwarnextra { get; set; }
        public string Bankcode { get; set; }
        public string Empbankacc { get; set; }
        public byte IsHd { get; set; }
        public byte? Medicaltype { get; set; }
        public byte? Pmedicaltype { get; set; }
        public string Pmedicalidno { get; set; }
        public string Pmedicalissue { get; set; }
        public DateTime? Pmedicaldate { get; set; }
        public DateTime? Pmedicalenddate { get; set; }
        public byte? Endworkreason { get; set; }
        public byte? Contracttype { get; set; }
        public byte? Endworkfree { get; set; }
        public byte? Origintaxtype { get; set; }
        public decimal Empsal08 { get; set; }
        public decimal Empsal09 { get; set; }
        public byte Taxsal01 { get; set; }
        public byte Taxsal02 { get; set; }
        public byte Taxsal03 { get; set; }
        public byte Taxsal04 { get; set; }
        public byte Taxsal05 { get; set; }
        public byte Taxsal06 { get; set; }
        public byte Taxsal07 { get; set; }
        public byte Taxsal08 { get; set; }
        public byte Taxsal09 { get; set; }
        public string Candidatestatus { get; set; }
        public string Recpersoncode { get; set; }
    }
}
